#
# Copyright (c) 2022 Kaiserpfalz EDV-Service, Roland T. Lichti
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

spring:
  application: Librarian
  version: 1.0.0-SNAPSHOT

  security:
    oauth2:
      client:
        provider:
          kaiserpfalz-edv:
            user-name-attribute: preferred_username
            issuer-url: ${OIDC_ISSUER}
        registration: 
          kaiserpfalz-edv:
            client-id: ${OIDC_CLIENT}
            client-secret: ${OIDC_CREDENTIAL}
            authorization-grant-type: authorization_code
            scope: openid
    resourceserver:
      jwt:
        issuer-url: ${OIDC_ISSUER}

  https:
    enabled: TRUE

  http:
    enabled: TRUE

  banner:
    location: classpath:/banner.txt