#
# Copyright (c) 2022 Kaiserpfalz EDV-Service, Roland T. Lichti
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

spring:
  application: Librarian
  version: 1.0.0-SNAPSHOT

  security:
    oauth2:
      client:
        provider:
          kaiserpfalz-edv:
            user-name-attribute: preferred_username
            issuer-uri: ${OIDC_ISSUER}
            authorization-uri: ${OIDC_PROVIDER_BASE}/auth
            token-uri: ${OIDC_PROVIDER_BASE}/token
            user-info-uri: ${OIDC_PROVIDER_BASE}/userinfo
        registration: 
          kaiserpfalz-edv:
            client-id: ${OIDC_CLIENT}
            client-secret: ${OIDC_CREDENTIAL}
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: http://localhost:8080/
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER}
          jwk-set-uri: ${OIDC_PROVIDER_BASE}

  https:
    enabled: FALSE

  http:
    enabled: TRUE

  banner:
    location: classpath:/banner.txt

  jpa:
    open-in-view: FALSE

hibernate:
  cache:
    "use_second_level_cache": TRUE
    region:
      "factory_class": org.hibernate.cache.ehcache.EhCacheRegionFactory


logging:
  level:
    root: INFO
    "org.springframework": INFO
    "de.kaiserpfalzedv": DEBUG

server:
  port: 8080

management:
  address: 127.0.0.1
  port: 8090

  security:
    enabled: FALSE

  endpoints:
    health:
      time-to-live: 15000
    web:
      exposure:
        include: ['prometheus','health','ready','info']

  endpoint:
    health:
      probes:
        enabled: true

  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true